#!/bin/bash

a="dta2"
m="dtm1 dtm2 dtm3 dtm4"
w="dtw1 dtw2 dtw3 dtw4 dtw5 dtw6 dtw7"

for n in $a $m $w
do
   nc -w 1 -z $n 22 &>/dev/null
   if [ "$?" == "0" ]; then
      ssh $n exit &>/dev/null
      [ "$?" == "0" ] && echo -n "$n ssh ok"

      ssh $n 'java -version' &>/dev/null
      [ "$?" == "0" ] && echo -n ", jdk8 ok" 
    
      ssh $n 'which python3' &>/dev/null
      if [ "$?" == "0" ]; then
         echo ", python3 ok"
      else
         echo ""
      fi
   fi
done
