#!/bin/bash

m="dtm1"
w=$(cat /etc/hosts | grep -e ' dtw[0-9]' | cut -d' ' -f2)

ssh bigred@"$m" hadoop-daemon.sh start namenode &>/dev/null
sleep 10; nc -w 5 -z $m 8020 &>/dev/null
[ "$?" != 0 ] && echo "pls formathdfs first" && exit 1
echo "$m: Name Node Started"

ssh bigred@"$m" hadoop-daemon.sh start secondarynamenode &>/dev/null
[ "$?" == "0" ] && echo "$m: Secondary Name Node started"

for n in $w
do
   nc -w 5 -z $n 22 &>/dev/null
   if [ "$?" == "0" ]; then
      ssh bigred@$n hadoop-daemon.sh start datanode &>/dev/null
      [ "$?" == "0" ] && echo "$n: Data Node started"
   fi
done
